### ISSUE TITLE
Clean up BPMN moddle copy and paste

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1708]
__What should we do?__

There is a couple of issue we detected in our BPMN copy and paste implementation:

* [x] `moddleCopy.canCopyProperty` is used in stateful manner :arrow_right: https://github.com/bpmn-io/bpmn-js/pull/1707
    * In [`GroupBehavior`](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/modeling/behavior/GroupBehavior.js#L176), adding category to root element :arrow_right: should add category value on shape addition only
    * In ModdleCopy -> assign id on copy, not on insert: https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/copy-paste/ModdleCopy.js#L271
* [x] Copied tree gets modified after copy (https://github.com/bpmn-io/bpmn-js/issues/798) :arrow_right: https://github.com/bpmn-io/bpmn-js/pull/1707
* [x] Copy of references incompatible with serialization (https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/modeling/behavior/BoundaryEventBehavior.js, `processRef`, https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/modeling/behavior/GroupBehavior.js#L176) :arrow_right: https://github.com/bpmn-io/bpmn-js/pull/1707
* [x] Root element copy behaviors ([boundary event behavior](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/modeling/behavior/BoundaryEventBehavior.js#L64), but potentially also the [general root element reference behavior](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/modeling/behavior/RootElementReferenceBehavior.js)) copy the `processRef` (process is an instance of `bpmn:RootElement` unintentinally :arrow_right: https://github.com/bpmn-io/bpmn-js/pull/1707

__Why should we do it?__

Improve the robustness of our copy + paste implementation; eventually support cut + paste.

----

Out of scope: 

* [ ] Ids are never unclaimed when overridden during copy (cf. https://github.com/camunda/camunda-modeler/issues/3085)
* [ ] `camunda-bpmn-moddle` still has its own behaviors (when it should not!) https://github.com/camunda/camunda-bpmn-moddle/issues/110
