### ISSUE TITLE
Investigate: Document our APIs in a user friendly way

### ISSUE THREAD

**Issue by ricardomatias** [bpmn-io/bpmn-js#233]
Adding a (self) hosted solution with up to date documentation.

[**ReadMe.io**](https://readme.io/) could be a great option since it's a well built, easy to use system and free for open source.

### Primary Use Case

Users should learn about our public API, i.e. the [Overlays](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/overlays/Overlays.js) service or the main entry points into bpmn-js.

* Only some APIs are public
* We want to be able to provide information about these directly in code or as close as possible to it (distance means harder to maintain)
* We want documentation to be generated to HTML + published somewhere
* Linking to GitHub or other parts of the documentation should work

### Options

* Using a library
* Parsing stuff manually and feeding it into a page generator, i.e. [kartoffeldruck](https://github.com/nikku/kartoffeldruck) or the like

### Tasks

* [ ] generate documentation for `Overlays` + `EventBus` (in `MD` format)
* [ ] investigate linking between `Overlays` -> `EventBus`
* [ ] create HTML from the MD documentation; focus on readability / public

**Comment by nikku** [comment]
Some things to take into account:

* Parsing of JSDoc + Markdown
* Generating HTML
* Versioning
* Only publishing public API (we need to decide on what this is)

**Comment by nikku** [comment]
Related to bpmn-io/diagram-js#78
