### ISSUE TITLE
Create documentation prototype

### ISSUE THREAD

**Issue by ricardomatias** [bpmn-io/bpmn-js#298]
Adding a (self) hosted solution with up to date documentation.

### Primary Use Case

Users should learn about our public API, i.e. the [Overlays](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/overlays/Overlays.js) service or the main entry points into bpmn-js.

* Only some APIs are public
* User / Dev guides
* We want to be able to provide information about these directly in code or as close as possible to it (distance means harder to maintain)
* We want documentation to be generated to HTML + published somewhere
* Linking to GitHub or other parts of the documentation should work
* Being able to search the documentation
* Navigation (tree structure)

### Tasks

* [x] generate documentation for `Overlays` + `EventBus` (in `MD` format)
* [x] investigate linking between `Overlays` -> `EventBus`
* [x] create HTML from the MD documentation; focus on readability / public

### Tools
* [jsDoc-parse](https://github.com/jsdoc2md/jsdoc-parse)
* [ddata](https://github.com/jsdoc2md/ddata)
* [dmd](https://github.com/jsdoc2md/dmd)
* [marked](https://github.com/chjj/marked)
* [nunjucks](https://mozilla.github.io/nunjucks)
* [kartoffeldruck](https://github.com/nikku/kartoffeldruck)

Possible control flow: Stream `.js` -> jsDoc-parse -> filtering -> output (dmd/marked)

**Comment by ricardomatias** [comment]
Added changes in the following projects: bpmn-js (**documentation** branch), diagram-js (**docs** branch).
