### ISSUE TITLE
I can model lanes

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#316]
Users can model lanes.

#### Tasks

* [x] Lanes can be added to a participant from the palette
   * [x] Get all the elements originally in the parent
* [x] Lanes can be removed from a participant
* [x] Lanes can be resized (vertically)

**Comment by gerardo-navarro** [comment]
Nice, I have been waiting for this feature. Good job.
