### ISSUE TITLE
I can model groups

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#343]
Groups are the BPMN way of clustering elements and help to make diagrams easier to understand.

__Tasks__

* [x] Render group names (#844) 
* [x] A group can be resized freely (#956)
* [x] Elements can be placed inside groups (#959)
* [x] A group can only be moved on the borders (#960)
* [x] Groups are rendered always on top (#979) 
* [x] A group can be created from the palette (#954) 
* [x] A group can be copied and pasted (#958)
* [x] A group can be double-clicked to edit the name (#955)
* [x] A group's name can be modified through the PropertiesPanel (https://github.com/bpmn-io/bpmn-js-properties-panel/issues/278)
* [x] Participants should not be resized when a group is dropped/resized on its borders (#1043)

__Open issues__ (and stuff for the future)

* Group label should be move after resizing (#1051)  
* Disable "drop allowed" overlay when moving label over group (#1054)
* Confusing behavior on group copy (#1055) 

__Additional Topics__

* <del>A category defines a groups name and may be referenced by multiple Group elements. Do we want to allow for that usage in our tool? If not we may run into compatibility issues with other tools.</del> https://github.com/bpmn-io/bpmn-js/pull/1017
* <del>When deleting a group, should also the referenced category be deleted?</del> cf. https://github.com/bpmn-io/bpmn-js/pull/1017
* <del>Upon move, a group is put in the most _outer_ available container for `Artifact` elements. Investigate whether this already done</del> #1053 
* Groups hold an indirect reference to diagram elements that belong to it (via `Group > categoryValueRef (CategoryValue) > categorizedFlowElements (List<FlowElement>)`). Should we maintain it?
* Right now, a group's ContextPad has only one option (deleting). Should we consider adding more actions (e.g. TextAnnotation)?

--- 

Related to https://github.com/bpmn-io/bpmn-js/issues/844.

**Comment by TarantoHestis** [comment]
Is this task planned?

**Comment by nikku** [comment]
Not on our immediate road map.

**Comment by jwaligora** [comment]
I know this seems basic and potentially superfluous, but at the business level it's essential as it can be used to denote process states, which are otherwise not supported by BPMN 2.0 (as per slide 6 of [link](http://www.omg.org/news/meetings/workshops/SOA-HC/presentations-2011/14_MT-2_Brookshier.pdf)). 
...I saw the Stack Overflow note on use of Data Object with DataState element. Though logically sound, it's simply not visually appeasing to the executive audiences.

**Comment by nikku** [comment]
Another alternative which may be even more appealing is [colors](https://bpmn.io/blog/posts/2016-colors-bpmn-js.html): 

![image](https://user-images.githubusercontent.com/58601/40429972-3c43175e-5ea4-11e8-826a-460880b196ea.png)

**Comment by AadneEM** [comment]
What is the status on the implementation of this? Is it stil low priority?

**Comment by nikku** [comment]
Received some attention lately and will likely make it onto our 2019 roadmap. 

:crossed_fingers:

**Comment by pinussilvestrus** [comment]
> Received some attention lately and will likely make it onto our 2019 roadmap.
> 
> 🤞

As part of our next milestone, we are going to implement group support 🎉 
This issue should act as an overview ticket. I'll open more issues including single tasks after defining the scope.
