### ISSUE TITLE
Rework multi-selection move across parent borders

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#354]
Multi-Selection move got increasingly complicated with lanes. The reason is that we always force a parent change and do not visually indicate what the actual new parent is.

#### Tasks

* [x] Implement a _keep parent_ move. As long as the parent of the primary selection does not change, it is assumed that all other elements are moved without changing their parents, too.
* [x] If the parent of the primary selection changes,  move all elements to that new parent on drop.
* [x] Remove the `hasSameParent` restriction (`BpmnRules`) when moving multiple elements.

#### Notes

* No need to test/fix this in conjunction with `Lanes`. The problem can already be adressed in the context of `Process` / `SubProcess`.
