### ISSUE TITLE
Add global Connect tool

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#474]
Allow users to connect elements in birds eye view, i.e. when working with huge collaboration diagrams:

![image](https://cloud.githubusercontent.com/assets/58601/13247928/388f0d48-da1c-11e5-8036-b4207f68b1c7.png)

### Tasks

* [x] connects two elements with each other by dragging from one element to another
* [x] is activated via keyboard shortcut
* [x] is activated via palette icon
* [x] highlight palette icon when active
