### ISSUE TITLE
Investigate form field id import issue

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#493]
bpmn-js falsefully assumes that `id` fields are always unique.

This assumption is only correct in the BPMN namespaces (BPMN, BPMNDI, DI) and does not hold true for extension namespaces, i.e. [Camunda](https://camunda.org/).

### Related Issues

Depends on the following issues and underlying _breaking changes_ (require minor version bump):

* [x] bpmn-io/moddle#13 - add explicit `isId` meta-data
* [x] bpmn-io/moddle-xml#14 - import and collect only elements with explicit ids
* [x] bpmn-io/bpmn-moddle#41 - expose id properties correctly

On all these projects _and_ bpmn-js reside on the `493-id-properties` branch.

### Additional Notes

Additionally [this commit in camunda/camunda-bpmn-moddle](https://github.com/camunda/camunda-bpmn-moddle/commit/03a79279a757182f9106db72b12bc46ad7686ece), (__needs merge, too__) verifies that we correctly ignore id properties that are not flagged with `isId=true`.

**Comment by meyerdan** [comment]
XSD has an "Id" type. An attribute can be defined of type `xsd:ID` as BPMN does for the [attribute Id on the base element](https://github.com/camunda/camunda-bpm-platform/blob/master/engine/src/main/resources/org/camunda/bpm/engine/impl/bpmn/parser/Semantic.xsd#L98): 

```
<xsd:attribute name="id" type="xsd:ID" use="optional"/>
```

But I think that it is valid to define an attribute named "id" as plain string:

```
<xsd:attribute name="id" type="xsd:string" use="optional"/>
```

See also: http://www.w3schools.com/xml/schema_dtypes_string.asp (Table on the end of the page)

**Comment by nikku** [comment]
We need to fix this from the bottom up, starting at moddle. I added respective issues to the description.

**Comment by nikku** [comment]
@meyerdan Thanks for the spec hint. The actual problem is that we overlooked the ID property definition in `DI.xsd` when implementing ID handling in moddle. We added the _if property is called id hack_ because of that :wink:.

**Comment by meyerdan** [comment]
Xml... great fun. :fireworks:

**Comment by nikku** [comment]
See updated issue description for review hints.
