### ISSUE TITLE
Attach boundary event to default position when dropping on task

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#518]
When trying to model a boundary event it may not be immediately obvious that it has to be attached to a task's border.

For users it would be more intuitive to not reject the modeling operation when dropping it inside the task but to automatically attach the event to a _default position_.
#### Tasks
- [ ] create intermediate event on collapsed activities (everything excluding expanded sub-processes) is _always allowed_.
- [ ] when dropping on element, _attach to default position_ instead
- [ ] snap during dragging to indicate the attach

**Comment by nikku** [comment]
We offer strong snapping feedback with recent versions of the tool:

![capture 4tc24u_optimized](https://user-images.githubusercontent.com/58601/61855624-b9764300-aec0-11e9-9b19-e3f437f63601.gif)

I'm closing this issue as we have no intention to go beyond the current interaction right now.
