### ISSUE TITLE
I can model a new task in a process

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#6]
-   [x] from an existing element (start event or task), a task that follows that element can be created
  -  [x] exception: endevent
-   [x] the new task is automatically connected with a sequence flow
-   [x] after creating the task, the user is automatically in label editing mode
#### Tasks
-   [x] basic implementation
-   [x] sequence flow points from edge to edge
-   [x] context pad integration
