### ISSUE TITLE
Fix bpmn-moddle bugs

### ISSUE THREAD

**Issue by Nikku** [bpmn-io/bpmn-js#64]
A few bugs currently lead to XML being not correctly imported / exported:

* [x] bpmn-io/bpmn-moddle#4 Correctly serialize callActivity#calledElement
* [x] bpmn-io/bpmn-moddle#3 Correctly serialize data-types via xsi:type
* [x] bpmn-io/bpmn-moddle#2 Incorrect handling of expression elements
